---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['KITCHEN_AWS_SSH_KEY_ID'] %>
  region: <%= ENV['KITCHEN_AWS_REGION'] %>
  availability_zone: <%= ENV['KITCHEN_AWS_REGION_ZONE'] %>
  require_chef_omnibus: true
  subnet_id: <%= ENV['KITCHEN_AWS_SUBNET_ID'] %>
  instance_type: <%= ENV['KITCHEN_EC2_INSTANCE_TYPE'] %>
  associate_public_ip: <%= ENV['KITCHEN_EC2_PUBLIC_IP'] %>
  security_group_ids: <%= ENV['KITCHEN_EC2_SECURITY_GROUP_IDS'] %>
  interface: <%= ENV['KITCHEN_EC2_INTERFACE'] %>
  retryable_tries: 120

transport:
  ssh_key: <%= ENV['KITCHEN_AWS_KEY_FILE'] %>
  connection_timeout: 10
  connection_retries:

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: /Users/hlee/.puppetlabs/etc/code/modules
  require_chef_for_busser: false

platforms:
  - name: windows-2012r2
    driver:
      image_id: <%= ENV['WIN_2012_R2_AMI_ID'] %>
    # image_id: ami-83a5bce2
suites:
  - name: default
    manifest: /Users/hlee/official_toolbox/puppet-cloudpassage/manifests/site_windows.pp

