---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['KITCHEN_AWS_SSH_KEY_ID'] %>
  region: <%= ENV['KITCHEN_AWS_REGION'] %>
  availability_zone: <%= ENV['KITCHEN_AWS_REGION_ZONE'] %>
  require_chef_omnibus: true
  subnet_id: <%= ENV['KITCHEN_AWS_SUBNET_ID'] %>
  instance_type: <%= ENV['KITCHEN_EC2_INSTANCE_TYPE'] %>
  associate_public_ip: <%= ENV['KITCHEN_EC2_PUBLIC_IP'] %>
  security_group_ids: <%= ENV['KITCHEN_EC2_SECURITY_GROUP_IDS'] %>
  interface: <%= ENV['KITCHEN_EC2_INTERFACE'] %>
  retryable_tries: 120

transport:
  ssh_key: <%= ENV['KITCHEN_AWS_KEY_FILE'] %>
  connection_timeout: 10
  connection_retries:

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: /etc/puppetlabs/code/modules
  require_chef_for_busser: true

platforms:
  - name: rhel-7.3
    driver:
      image_id: <%= ENV['RHEL_73_AMI_ID'] %>
      user_data: <%= ENV['KITCHEN_EC2_USER_DATA'] %>
    transport:
      username: <%= ENV['RHEL_73_USER'] %>
  - name: oracle-6
    driver:
      image_id: <%= ENV['ORACLE_6_AMI_ID'] %>
      user_data: <%= ENV['KITCHEN_EC2_USER_DATA'] %>
    transport:
      username: <%= ENV['ORACLE_6_USER'] %>
  - name: centos-7
    driver:
      image_id: <%= ENV['CENTOS_7_AMI_ID'] %>
      user_data: <%= ENV['KITCHEN_EC2_USER_DATA'] %>
    transport:
      username: <%= ENV['CENTOS_7_USER'] %>
  - name: debian-8
    driver:
      image_id: <%= ENV['DEBIAN_8_AMI_ID'] %>
      user_data: <%= ENV['KITCHEN_EC2_USER_DATA'] %>
    transport:
      username: <%= ENV['DEBIAN_8_USER'] %>
  - name: amazon-linux-20160901
    driver:
      image_id: <%= ENV['AMZN_LIN_2016_09_AMI_ID'] %>
      user_data: <%= ENV['KITCHEN_EC2_USER_DATA'] %>
    transport:
      username: <%= ENV['AMZN_LIN_2016_09_USER'] %>

suites:
  - name: linux
    provisioner:
      manifest: site_linux.pp
      custom_facts:
        halo_agent_key: <%= ENV['HALO_AGENT_KEY'] %>
